# 🏠 Gayrimenkul Tahmincisi

🎯Aşağıdaki challenge'da şunlar arasında bir ***DOĞRUSAL İLİŞKİ*** olup olmadığını anlamaya çalışacağız:
- bir dairenin **fiyatı** (her daire için **hedefimiz**)
- ve yüzey alanı, yatak odası sayısı vb. gibi **özellikler**

❗️ Bu challenge'da Pandas yasaklanmıştır ❗️

😁 Bu alıştırma boyunca arkadaşın olacak [NumPy belgelerine](https://docs.scipy.org/doc/numpy/reference/) hoş geldin.

👉 Ayrıca bu [NumPy cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) adresinde yardım bulabilirsin

In [1]:
import numpy as np

🌆 Aşağıda 4 dairenin verilerini topladığımızı varsay: 
- **özellikleri**:
    - `surface` (kare feet)
    - `bedrooms`
    - `floors` 
- **hedefleri**:
    - `price` (bin USD cinsinden)

|daireler |surface (kare feet)|yatak odası|katlar|price (bin USD)|
|------|-------------|--------|------|------------|
|flat1 |620|1|1|244|
|flat2 |3280|4|2|671|
|flat3 |1900|2|2|504|
|flat4 |1320|3|3|510|

👉 **Bir dairenin fiyatını tahmin etmenin** ilk yaklaşımı **hedef ve özellikler arasında doğrusal bir ilişki bulmaya** çalışmaktır (*yani fiyat ile (yüzey, yatak odası, kat) arasında*), aşağıdaki **$n = 4$ doğrusal denklem sistemi ile $p = 4$ bilinmeyen değişken** çözerek:

$$\begin{cases}
    244 = \theta_0 + 620\theta_1 + 1\theta_2 + 1\theta_3 \\
    671 = \theta_0 + 3280\theta_1 + 4\theta_2 + 2\theta_3 \\
    504 = \theta_0 + 1900\theta_1 + 2\theta_2 + 2\theta_3 \\
    510 = \theta_0 + 1320\theta_1 + 3\theta_2 + 3\theta_3 \\
\end{cases}$$

bu da bir matris denklemine çevrilebilir:

$$\boldsymbol y = \boldsymbol {X \cdot \theta}$$

$$\begin{bmatrix}
    244 \\
    671 \\
    504 \\
    510
\end{bmatrix}_{4 \times 1} = \begin{bmatrix}
    1 & 620 & 1 & 1 \\
    1 & 3280 & 4 & 2 \\
    1 & 1900 & 2 & 2 \\
    1 & 1320 & 3 & 3
\end{bmatrix}_{4 \times 4} \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3
\end{bmatrix}_{4 \times 1}$$

burada:
* $\boldsymbol y$ **`hedef`**, `Price` vektörüdür
* $\boldsymbol X$ **`özelliklerin matrisi`** temsil eder
* $\boldsymbol {\theta} = \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3
\end{bmatrix}$ (*theta*) bulunacak **katsayıları/değişkenleri/bilinmeyenleri** temsil eden vektördür

----

🤓 Burada, **özelliklerimizin** katsayılarını temsil etmek için Yunanca harfi `theta` $\boldsymbol \theta = \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3 \\
\end{bmatrix}$ kullanıyoruz:

- Yüzeyi, yatak odası ve katı olmayan bir daire $\theta_0$ kadar mal olur
- Bir kare ayağın artması - *yatak odası sayısı ve kat numarası sabit tutulduğunda* - fiyatı $\theta_1$ bin USD kadar artırır
- Ek bir yatak odası - *yüzey ve kat numarası sabit tutulduğunda* - fiyatı $\theta_2$ bin USD kadar artırır
- Bir kat numarasının artması - *yüzey ve yatak odası sayısı sabit tutulduğunda* - fiyatı $\theta_3$ bin USD kadar artırır

----

😉 Bu doğrusal denklem sistemini çözmeyi başarırsak (yani $\theta_0$, $\theta_1$, $\theta_2$, $\theta_3$ bulursak), herhangi bir yeni dairenin fiyatı aşağıdaki formül kullanılarak tahmin edilebilir: $$y_{newflat} = \boldsymbol x_{newflat} \cdot \boldsymbol \theta$$

## (1) `features` matrisini $\boldsymbol X$ tanımla:

❓ 4 gözlem için 3 özelliğin (yüzey, yatak odası, katlar) değerlerini depolayan bir $(4,3)$ `numpy.ndarray` oluştur.

In [2]:
X = np.array([
    [620,  1, 1],
    [3280, 4, 2],
    [1900, 2, 2],
    [1320, 3, 3]
])

❓ Bu ***np.array***'in ***shape***'ini, ***size***'ını ve ***dim***'ini double-check et

In [7]:
X.shape
X.size
X.ndim

2

❓ Doğrusal denklem sistemini temsil eden $(4,4)$ matrisi $\boldsymbol X$ oluşturmak için $ = \begin{bmatrix}
    1 \\
    1 \\
    1 \\
    1 \\
\end{bmatrix}$ birlerinin "constant" vektörünü ekle

<details>
    <summary><i>Açıklamalar</i></summary>

🤔 Muhtemelen fark ettiğin gibi, doğrusal denklem sistemi 4 denklemde görünen bir $\theta_0$ katsayısını içeriyor.

❗️ Doğrusal regresyon çizgisinin y-kesişimini temsil etmek için ek bir özelliğe ihtiyacımız var

_Not_ : `price` ve özellikler arasında sıkı bir doğrusal ilişki yerine bir [affine relation](https://math.stackexchange.com/questions/275310/what-is-the-difference-between-linear-and-affine-function) hakkında konuşuyoruz (_Bkz. Decision Science Module_)
    
</details>

In [12]:
x0= np.ones((4,1))
x0

array([[1.],
       [1.],
       [1.],
       [1.]])

In [13]:
X_features = np.array([
    [620,  1, 1],
    [3280, 4, 2],
    [1900, 2, 2],
    [1320, 3, 3]
])

X = np.hstack((x0, X_features))

X

array([[1.00e+00, 6.20e+02, 1.00e+00, 1.00e+00],
       [1.00e+00, 3.28e+03, 4.00e+00, 2.00e+00],
       [1.00e+00, 1.90e+03, 2.00e+00, 2.00e+00],
       [1.00e+00, 1.32e+03, 3.00e+00, 3.00e+00]])

**🧪 Kodunu kontrol et!**

In [14]:
from nbresult import ChallengeResult

result = ChallengeResult('features',
    features=X
)
result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/doganalper/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/doganalper/code/data_real_estate_estimator/tests
plugins: typeguard-4.4.2, anyio-4.8.0
collecting ... collected 3 items

test_features.py::TestFeatures::test_X_shape PASSED                      [ 33%]
test_features.py::TestFeatures::test_features_order PASSED               [ 66%]
test_features.py::TestFeatures::test_x0_is_ones PASSED                   [100%]

============================== 3 passed in 0.14s ===============================


💯 You can commit your code:

git add tests/features.pickle

git commit -m 'Completed features step'

git push origin master



## (2) `Prices`'ın $\boldsymbol y$ vektörünü tanımla

$\boldsymbol y  = \begin{bmatrix}
    244 \\
    671 \\
    504 \\
    510
\end{bmatrix}$

❓ Matris gösterimimiz $\boldsymbol y  = \boldsymbol {X\cdot \theta}$ ile eşleştirmek için $\boldsymbol y$'nin shape'i ne olmalı? Aşağıda $\boldsymbol y$'yi tanımla. ❓

<details>
    <summary><i>İpucu</i></summary>

$\boldsymbol y$ bir $(4,1)$ array olmalı, dikey olarak temsil edilen düz bir "vektör" eşdeğeri
</details>

In [15]:
y = np.array([
    [244],
    [671],
    [504],
    [510]
])


**🧪 Kodunu kontrol et!**

In [16]:
from nbresult import ChallengeResult

result = ChallengeResult('target',
    target=y
)
result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/doganalper/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/doganalper/code/data_real_estate_estimator/tests
plugins: typeguard-4.4.2, anyio-4.8.0
collecting ... collected 1 item

test_target.py::TestTarget::test_shape PASSED                            [100%]

============================== 1 passed in 0.08s ===============================


💯 You can commit your code:

git add tests/target.pickle

git commit -m 'Completed target step'

git push origin master



## (3) Sistemin çözümünü bul

⏰Şimdi katsayıların $\boldsymbol \theta = \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3
\end{bmatrix}$ vektörünü bulmanın zamanı!

👍 Denklemin çözümü:
 
$$ \large \boldsymbol X \cdot \boldsymbol \theta = \boldsymbol y 
\large \iff \boldsymbol X^{-1} \cdot \boldsymbol X \boldsymbol \cdot \theta = \boldsymbol X^{-1} \cdot \boldsymbol y 
\large \iff \boldsymbol \theta = \boldsymbol X^{-1} \cdot \boldsymbol y
$$

burada $\large \boldsymbol X^{-1}$, $\large \boldsymbol X$'in tersidir.

In [17]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.64516129e+00,  4.42419702e-17, -2.90322581e-01,
        -3.54838710e-01],
       [-5.37634409e-04, -2.50426246e-19,  1.07526882e-03,
        -5.37634409e-04],
       [ 3.70967742e-01,  5.00000000e-01, -1.24193548e+00,
         3.70967742e-01],
       [-6.82795699e-01, -5.00000000e-01,  8.65591398e-01,
         3.17204301e-01]])

👉 Aşağıdaki eşitliği test ederek tersinin çalışıp çalışmadığını kontrol edebilirsin:

$$\boldsymbol X^{-1} \cdot\boldsymbol X = \boldsymbol I_4$$
burada $\boldsymbol I_4$ $ 4 \times 4 $ birim matrisidir $ \begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1
\end{bmatrix}$

In [22]:
I4 = np.eye(4)
I4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

👉 Şimdi $\boldsymbol X^{-1} \boldsymbol X$'i hesapla:

In [23]:
X_inv @ X

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.22044605e-16],
       [-3.25260652e-19,  1.00000000e+00, -8.67361738e-19,
        -4.33680869e-19],
       [ 3.33066907e-16,  6.25277607e-13,  1.00000000e+00,
         2.22044605e-16],
       [-2.77555756e-16, -5.11590770e-13, -6.66133815e-16,
         1.00000000e+00]])

❓ $\boldsymbol I_4$'e benziyor mu? ❓

⛔️ Benzemiyorsa, muhtemelen $\boldsymbol X^{-1}$ ve $\boldsymbol X$ arasındaki çarpımı gerçekleştirmek için `*` operatörünü kullandın. Burada matris çarpımını yapmak istiyoruz. Bunu yapmak için doğru NumPy yöntemini (veya kısaltılmış operatörü) bul.

✅ Benziyorsa, elde edilen çarpımda tam olarak sıfır ve birler elde edemediğini fark etmiş olabilirsin. Emin olmak için sonucunu kontrol etmek amacıyla [`numpy.allclose()`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html?highlight=allclose#numpy.allclose) yöntemini dene:

In [24]:
np.allclose(X_inv @ X, I4)

True

🎉 Son olarak aşağıdaki formülü kullanarak `theta`'yı hesaplayabilirsin: $ \large \boldsymbol \theta = \boldsymbol X^{-1}\cdot \boldsymbol y $:

In [26]:
theta = X_inv @ y
theta

array([[ 74.12903226],
       [  0.13655914],
       [-10.72580645],
       [ 95.93010753]])

**🧪 Kodunu kontrol et!**

In [27]:
from nbresult import ChallengeResult

result = ChallengeResult('solution',
    theta=theta
)
result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/doganalper/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/doganalper/code/data_real_estate_estimator/tests
plugins: typeguard-4.4.2, anyio-4.8.0
collecting ... collected 2 items

test_solution.py::TestSolution::test_theta0_is_correct PASSED            [ 50%]
test_solution.py::TestSolution::test_theta_shape PASSED                  [100%]

============================== 2 passed in 0.12s ===============================


💯 You can commit your code:

git add tests/solution.pickle

git commit -m 'Completed solution step'

git push origin master



## (4) Yeni bir dairenin fiyatının tahmini

Sonunda sistemi çözerek $\boldsymbol \theta$'yı buldun ve şimdi bu özelliklere sahip 5. bir dairenin `Price`'ını (bin $ cinsinden) tahmin edebilirsin:

- `Surface`: 3000 $ft^2$
- `Bedrooms`: 5 
- `Floors`: 1

aşağıdaki formül ile:

$$y_{flat5} = \boldsymbol x_{flat5} \cdot \boldsymbol \theta$$

In [30]:
x_flat5 = np.array([[1, 3000, 5, 1]])
x_flat5.shape
y_flat5 = x_flat5 @ theta
y_flat5

array([[526.10752688]])

## (5) Gerçeklik-kontrol

❗️ Gerçekte, bir dairenin fiyatı hiçbir zaman tamamen yüzey, yatak odası sayısı ve kat numarası tarafından belirlenmez.

Gerçek $y_{flat5}$ fiyatını tahmin edilen $526.000$ yerine $700.000$ olarak ölçtüğümüzü hayal edelim.

🤨 Modelimizi geliştirmek için bu yeni bilgiyi dikkate alabilir miyiz?

❓ Bu yeni dairenin bilgisini içermek için $ \large \boldsymbol X \cdot \boldsymbol \theta = \boldsymbol y$ doğrusal denklem sistemini güncelle.

In [34]:

x_flat5 = np.array([[1, 3000, 5, 1]])
y_flat5 = np.array([[700]])

X_new = np.vstack((X, x_flat5))

X_new.shape  # (5, 4)



(5, 4)

In [32]:
y_new = np.vstack((y, y_flat5))
y_new.shape  # (5, 1)

(5, 1)

👉 Güncellenmiş modelimizden 6. bir dairenin fiyatını tahmin etmeyi deneyelim.
Bunu yapmak için [`numpy.linalg.solve`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html) kullanarak $\boldsymbol X \cdot \boldsymbol \theta = \boldsymbol y$'dan $\boldsymbol \theta$'yı çözmeyi dene.

😲 Ne oluyor? Neden hata aldığını anlamaya çalış. Sonra, hücrenin altındaki açıklamayı aç.

In [35]:
theta_new = np.linalg.solve(X_new, y_new)


LinAlgError: Last 2 dimensions of the array must be square

<details>
    <summary><i>Açıklamalar</i></summary>

$ \large \boldsymbol X$ kare bir matris değil

$ \large  \rightarrow$ bu nedenle tersinin alınamaz: $ \large  \boldsymbol X^{-1}$ mevcut değil
 
$ \large  \rightarrow$ $ \large \boldsymbol \theta$, $ \large  \boldsymbol y = \boldsymbol X \cdot \boldsymbol \theta$'dan hesaplanamaz
    
😕 Sadece 3 özelliğin doğrusal kombinasyonu olarak bir dairenin tahmin edilen fiyatını hesaplamak için kapalı bir matematiksel formül bulmaktan oluşan ilk yaklaşımımız, gözlemlenen 5 dairemiz için **geçerli değildir**.

😉 ***Sürece güven!*** 

$ \large  \rightarrow$ Bunun yerine, gelecek haftalarda bu özellikler temelinde bir dairenin fiyatını **yaklaşıklaştırmak** için yöntemler öğreneceğiz.

Örneğin, $\large  \boldsymbol y = \boldsymbol X \cdot \boldsymbol \theta$ çözmek yerine, hata $ \large \\boldsymbol e = \\boldsymbol X \\cdot \\hat{\\boldsymbol \\theta} - \\boldsymbol y $'ü en aza indiren $ \large  \\hat{\\boldsymbol \\theta}$'yı bulabiliriz: Bu yaklaşım **Doğrusal Regresyon modeli** olarak adlandırılır

Bu yeni tahminci daha sonra $ \large  \\hat y_{flat_6} = \\boldsymbol x_{flat_6} \\cdot \\hat{\\boldsymbol \\theta}$ ile herhangi bir yeni daire için fiyatın **yaklaşık** bir tahminini vermek için kullanılabilir

</details>

🏁 Tebrikler!

💾 Sonraki challenge'a geçmeden önce notebook'u commit etmeyi ve push'lamayı unutma!